# Generated by Django 3.2.8 on 2021-12-14 17:30

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('maker', models.CharField(blank=True, max_length=100, null=True, verbose_name='maker')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='aircraft model')),
                ('year', models.DateField(blank=True, null=True, verbose_name='year produced')),
                ('seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of seats')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='aircraft price (m$)')),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('established', models.CharField(blank=True, max_length=255, null=True, verbose_name='established')),
                ('fleet_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='fleet size')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255, verbose_name='flight name')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start time (est)')),
                ('reach', models.DateTimeField(blank=True, null=True, verbose_name='reach date (est)')),
                ('distance', models.PositiveIntegerField(blank=True, null=True, verbose_name='distance (KM)')),
                ('passengers', models.PositiveIntegerField(blank=True, null=True, verbose_name='passengers numbers')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=50, null=True, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='state, province or municipality')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('airport', models.CharField(blank=True, max_length=500, null=True, verbose_name='airport')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ticket price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ticket price after discounts')),
                ('seat_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='seat number')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_destination', to='fly.location', verbose_name='destination location')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_flight', to='fly.flight', verbose_name='flight')),
            ],
        ),
    ]
