# Generated by Django 3.2.8 on 2021-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dflight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(blank=True, max_length=10, null=True)),
                ('callsign', models.CharField(blank=True, max_length=8, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dflight',
            },
        ),
    ]
